/*
# Generate test cases 

Initially happy path. A new UniqueKey.
*/
POST http://localhost:7071/api/OrchestrationZulu_HttpStart HTTP/1.1
Content-Type: application/json

{
    "name":"Zulu", 
    "uniqueKey":"1000"
}

HTTP/1.1 202  - Accepted
content-type: application/json
date: Wed, 02 Oct 2024 18:01:16 GMT
server: Kestrel
location: http://localhost:7071/runtime/webhooks/durabletask/instances/Main-Zulu-1000-24-10-02T06%3A06%3A17%3A049?code=CKKvhUY-uSSBeA15tM6VP3C5NitoRJTd-YqG_zHAJkFkAzFuf85JyA==
transfer-encoding: chunked
###
POST http://localhost:7071/api/OrchestrationZulu_HttpStart HTTP/1.1
Content-Type: application/json

{
    "name":"Zulu", 
    "uniqueKey":"1001"
}

HTTP/1.1 202  - Accepted
content-type: application/json
date: Wed, 02 Oct 2024 18:01:32 GMT
server: Kestrel
location: http://localhost:7071/runtime/webhooks/durabletask/instances/Main-Zulu-1001-24-10-02T06%3A06%3A22%3A405?code=CKKvhUY-uSSBeA15tM6VP3C5NitoRJTd-YqG_zHAJkFkAzFuf85JyA==
transfer-encoding: chunked
###
POST http://localhost:7071/api/OrchestrationZulu_HttpStart HTTP/1.1
Content-Type: application/json

{
    "name":"Zulu", 
    "uniqueKey":"1003"
}

HTTP/1.1 202  - Accepted
content-type: application/json
date: Wed, 02 Oct 2024 18:01:51 GMT
server: Kestrel
location: http://localhost:7071/runtime/webhooks/durabletask/instances/Main-Zulu-1003-24-10-02T06%3A06%3A43%3A037?code=CKKvhUY-uSSBeA15tM6VP3C5NitoRJTd-YqG_zHAJkFkAzFuf85JyA==
transfer-encoding: chunked